openapi: 3.0.1
info:
  title: OrderCompositeAPI
  description: API Definition of OrderCompositeAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/internal/orders
- url: https://localhost:8253/internal/orders
paths:
  /orders/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
