version: "3.9"

services:
  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf

  erp-service:
    build: ./erp-service
    container_name: erp-service
    ports:
      - "9001:9001"

  mes-service:
    build: ./mes-service
    container_name: mes-service
    ports:
      - "9002:9002"

  telemetry-store:
    image: node:18
    container_name: telemetry-store
    working_dir: /app
    volumes:
      - ./telemetry-store:/app
    command: ["node", "server.js"]
    ports:
      - "9100:9100"

