FROM ballerina/ballerina:2201.12.9

USER root
WORKDIR /app

COPY . .

RUN mkdir -p /app/target && chmod -R 777 /app
RUN bal build

EXPOSE 8293

CMD ["bal", "run", "target/bin/oem_visibility_agent.jar"]